### ISSUE TITLE
Set up problem

### ISSUE THREAD

**Issue by MIKEFIN** [papulke/face-of-art#60]
I was not able to install the code with python 2.7 because of the version conflicts on menpo.
I think a requirements.txt file with version fixing would be extremely useful to help others running the codes. Also,  sample data and folders for testing would help too.
It is a very fun project and I would love to be able to repeat it.

**Comment by papulke** [comment]
Hi @MIKEFIN, sorry for the delay!
I created a requirements.txt file using pip freeze in my research environment. not sure everything is relevant, but I hope it helps!
you can download the artistic faces dataset from here: http://www.faculty.idc.ac.il/arik/site/foa/artistic-faces-dataset.asp
